apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-app
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: iamsrt23/flask-k8s-app:latest  # Replace with your image
        ports:
        - containerPort: 5000
        command: ["python", "app.py"]  # Ensure this is correct for your app